service: aws-node-project

frameworkVersion: '2'

plugins:
  - serverless-offline
provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:
  graphql:
    handler: server.action
    environment:
      SLS_DEBUG: true
    events: 
      - http:
          path: api/v1/employee
          method: post
          cors: true